import { TabType, PipelineType, FixtureData } from '../types';
import {
  CTA_STORY_FIXTURES,
  TIPS_EDU_STORY_FIXTURES,
  COLLECTION_CATEGORY_STORY_FIXTURES,
  DAY_NIGHT_STORY_FIXTURES,
  MOODBOARD_STORY_FIXTURES,
  PRODUCT_SPECS_STORY_FIXTURES,
  STYLE_THIS_STORY_FIXTURES,
  MYTH_FACT_STORY_FIXTURES,
  PRODUCT_DESCRIPTION_STORY_FIXTURES,
  THIS_OR_THAT_STORY_FIXTURES,
  TIPS_EDU_FEED_FIXTURES,
  COLLECTION_CATEGORY_FEED_FIXTURES,
  MOODBOARD_1_FEED_FIXTURES,
  MOODBOARD_2_FEED_FIXTURES,
  ONE_PRODUCT_THREE_STYLES_FIXTURES,
  DAY_NIGHT_FEED_FIXTURES,
  PRODUCT_SHOWCASE_FEED_FIXTURES,
  PRODUCT_CLOSEUP_REEL_FIXTURES,
  DAY_NIGHT_REEL_FIXTURES,
  BEFORE_AFTER_REEL_FIXTURES,
  STYLE_REEL_SLIDESHOW_FIXTURES,
  MOODBOARD_REEL_FIXTURES,
  ONE_PRODUCT_THREE_STYLES_REEL_FIXTURES,
  ONE_AT_A_TIME_LIGHTS_REEL_FIXTURES,
  AD_COVER_FIXTURES,
} from './fixtures';

export interface PipelineConfig {
  type: NonNullable<PipelineType>;
  name: string;
  format: TabType;
  subtabIndex: number;
  subTabLabel: string;
  runEndpoint: string;
  statusEndpoint: string;
  stopEndpoint: string;
  countsEndpoint: string;
  moodboardEndpoint?: string;
  promptEndpoint?: string;
  totalPhases: number;
  phaseSummary: string;
  fixtures: Omit<FixtureData, 'completed'>[];
  hasMoodboard: boolean;
  hasPrompt: boolean;
}

export const PIPELINES: PipelineConfig[] = [
  // --- Story Pipelines ---
  {
    type: 'cta',
    name: 'CTA Story',
    format: 'story',
    subtabIndex: 0,
    subTabLabel: 'CTA',
    runEndpoint: '/api/cta/run',
    statusEndpoint: '/api/cta/status',
    stopEndpoint: '/api/cta/stop',
    countsEndpoint: '/api/cta/counts',
    moodboardEndpoint: '/api/cta/moodboard',
    promptEndpoint: '/api/cta/prompt',
    totalPhases: 6,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interior ➔ Claude Prompt ➔ Banana Blend ➔ Headline ➔ Layout Stamping',
    fixtures: CTA_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'tips-edu',
    name: 'Tips & Educational Story',
    format: 'story',
    subtabIndex: 1,
    subTabLabel: 'Tips & Educational',
    runEndpoint: '/api/tips-edu/run',
    statusEndpoint: '/api/tips-edu/status',
    stopEndpoint: '/api/tips-edu/stop',
    countsEndpoint: '/api/tips-edu/counts',
    moodboardEndpoint: '/api/tips-edu/moodboard',
    promptEndpoint: '/api/tips-edu/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interior ➔ Claude Prompt ➔ Banana Blend ➔ Layout Stamping',
    fixtures: TIPS_EDU_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'collec-story',
    name: 'Collection Category Story',
    format: 'story',
    subtabIndex: 2,
    subTabLabel: 'Collection Category',
    runEndpoint: '/api/collection-story/run',
    statusEndpoint: '/api/collection-story/status',
    stopEndpoint: '/api/collection-story/stop',
    countsEndpoint: '/api/collection-story/counts',
    moodboardEndpoint: '/api/collection-story/moodboard',
    promptEndpoint: '/api/collection-story/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interiors (3 slots) ➔ Claude Prompts ➔ Banana Blend (3 slots) ➔ 9:16 Grid & Overlays',
    fixtures: COLLECTION_CATEGORY_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'day-night-story',
    name: 'Day & Night Story',
    format: 'story',
    subtabIndex: 3,
    subTabLabel: 'Day & Night',
    runEndpoint: '/api/day-night-story/run',
    statusEndpoint: '/api/day-night-story/status',
    stopEndpoint: '/api/day-night-story/stop',
    countsEndpoint: '/api/day-night-story/counts',
    moodboardEndpoint: '/api/day-night-story/moodboard',
    promptEndpoint: '/api/day-night-story/prompt',
    totalPhases: 4,
    phaseSummary: 'Akeneo Scrape ➔ Krea AI Interior ➔ Claude Sonnet 5 Prompt ➔ Nano Banana Pro Day & Night Blending + Logo',
    fixtures: DAY_NIGHT_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'moodboard-story',
    name: 'Moodboard Story',
    format: 'story',
    subtabIndex: 4,
    subTabLabel: 'Moodboard Story',
    runEndpoint: '/api/moodboard-story/run',
    statusEndpoint: '/api/moodboard-story/status',
    stopEndpoint: '/api/moodboard-story/stop',
    countsEndpoint: '/api/moodboard-story/counts',
    moodboardEndpoint: '/api/moodboard-story/moodboard',
    promptEndpoint: '/api/moodboard-story/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea AI Interior ➔ Claude Sonnet 5 Prompt ➔ Banana Daytime Blend ➔ Logo ➔ Moodboard Card',
    fixtures: MOODBOARD_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'product-specs',
    name: 'Product Closeup w/ Specs Story',
    format: 'story',
    subtabIndex: 5,
    subTabLabel: 'Product Specs',
    runEndpoint: '/api/product-specs/run',
    statusEndpoint: '/api/product-specs/status',
    stopEndpoint: '/api/product-specs/stop',
    countsEndpoint: '/api/product-specs/counts',
    totalPhases: 2,
    phaseSummary: 'Akeneo Product Scrape & Specs Layout ➔ Nano Banana Pro 9:16 Blending & Airtable Upload',
    fixtures: PRODUCT_SPECS_STORY_FIXTURES,
    hasMoodboard: false,
    hasPrompt: false,
  },
  {
    type: 'style-this',
    name: 'Style This? Story',
    format: 'story',
    subtabIndex: 6,
    subTabLabel: 'Style This?',
    runEndpoint: '/api/style-this/run',
    statusEndpoint: '/api/style-this/status',
    stopEndpoint: '/api/style-this/stop',
    countsEndpoint: '/api/style-this/counts',
    moodboardEndpoint: '/api/style-this/moodboard',
    promptEndpoint: '/api/style-this/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interiors (4 slots) ➔ Claude Vision & Color ➔ Banana Blend ➔ Double-Tap & Pill Stamping',
    fixtures: STYLE_THIS_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'myth-fact-story',
    name: 'Myth & Fact Story',
    format: 'story',
    subtabIndex: 7,
    subTabLabel: 'Myth & Fact',
    runEndpoint: '/api/myth-fact-story/run',
    statusEndpoint: '/api/myth-fact-story/status',
    stopEndpoint: '/api/myth-fact-story/stop',
    countsEndpoint: '/api/myth-fact-story/counts',
    moodboardEndpoint: '/api/myth-fact-story/moodboard',
    promptEndpoint: '/api/myth-fact-story/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interiors ➔ Claude Prompts ➔ Debunk Cover ➔ Myth & Fact Blends ➔ Outro Slide & Upload',
    fixtures: MYTH_FACT_STORY_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'product-desc-story',
    name: 'Product Closeup w/ Description Story',
    format: 'story',
    subtabIndex: 8,
    subTabLabel: 'Product Description',
    runEndpoint: '/api/product-description-story/run',
    statusEndpoint: '/api/product-description-story/status',
    stopEndpoint: '/api/product-description-story/stop',
    countsEndpoint: '/api/product-description-story/counts',
    totalPhases: 2,
    phaseSummary: 'Akeneo Product Scrape & Description Layout ➔ Fal AI Nano Banana Pro 9:16 Description Card Blending',
    fixtures: PRODUCT_DESCRIPTION_STORY_FIXTURES,
    hasMoodboard: false,
    hasPrompt: false,
  },
  {
    type: 'this-or-that-story',
    name: 'This or That Story',
    format: 'story',
    subtabIndex: 9,
    subTabLabel: 'This or That',
    runEndpoint: '/api/this-or-that/run',
    statusEndpoint: '/api/this-or-that/status',
    stopEndpoint: '/api/this-or-that/stop',
    countsEndpoint: '/api/this-or-that/counts',
    totalPhases: 2,
    phaseSummary: 'Akeneo 2-Product Scrape & Watermark Template ➔ Fal AI Nano Banana Pro 9:16 Comparison Story Card',
    fixtures: THIS_OR_THAT_STORY_FIXTURES,
    hasMoodboard: false,
    hasPrompt: false,
  },

  // --- Feed Pipelines ---
  {
    type: 'tips-edu-feed',
    name: 'Tips & Educational Feed',
    format: 'feed',
    subtabIndex: 0,
    subTabLabel: 'Tips & Educational',
    runEndpoint: '/api/tips-edu-feed/run',
    statusEndpoint: '/api/tips-edu-feed/status',
    stopEndpoint: '/api/tips-edu-feed/stop',
    countsEndpoint: '/api/tips-edu-feed/counts',
    moodboardEndpoint: '/api/tips-edu-feed/moodboard',
    promptEndpoint: '/api/tips-edu-feed/prompt',
    totalPhases: 6,
    phaseSummary: 'Akeneo Scrape ➔ Krea 3 Interiors + Thumbnail ➔ Claude Vision Prompts ➔ Nano Banana Room Blends ➔ YOLO Item Tagging ➔ Final 3-Slide Layouts',
    fixtures: TIPS_EDU_FEED_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'collection-feed',
    name: 'Collection Category Feed',
    format: 'feed',
    subtabIndex: 1,
    subTabLabel: 'Collection Category',
    runEndpoint: '/api/collection-feed/run',
    statusEndpoint: '/api/collection-feed/status',
    stopEndpoint: '/api/collection-feed/stop',
    countsEndpoint: '/api/collection-feed/counts',
    totalPhases: 5,
    phaseSummary: '5-Room Krea Generation ➔ Claude Room Matching ➔ Targeted Akeneo Catalog Scraper ➔ Blending Prompt Engineering ➔ Nano Banana Pro 5-Slide Blending',
    fixtures: COLLECTION_CATEGORY_FEED_FIXTURES,
    hasMoodboard: false,
    hasPrompt: false,
  },
  {
    type: 'moodboard-1-feed',
    name: 'Moodboard #1 Feed',
    format: 'feed',
    subtabIndex: 2,
    subTabLabel: 'Moodboard #1',
    runEndpoint: '/api/moodboard-1-feed/run',
    statusEndpoint: '/api/moodboard-1-feed/status',
    stopEndpoint: '/api/moodboard-1-feed/stop',
    countsEndpoint: '/api/moodboard-1-feed/counts',
    moodboardEndpoint: '/api/moodboard-1-feed/moodboard',
    promptEndpoint: '/api/moodboard-1-feed/prompt',
    totalPhases: 6,
    phaseSummary: 'Krea Interior ➔ Claude Prompting ➔ Nano Banana Pro Blending + YOLO Item Tagging ➔ Local Brand Logo ➔ Material Swatch Moodboard ➔ Macro Close-up',
    fixtures: MOODBOARD_1_FEED_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'moodboard-2-feed',
    name: 'Moodboard #2 Feed',
    format: 'feed',
    subtabIndex: 3,
    subTabLabel: 'Moodboard #2',
    runEndpoint: '/api/moodboard-2-feed/run',
    statusEndpoint: '/api/moodboard-2-feed/status',
    stopEndpoint: '/api/moodboard-2-feed/stop',
    countsEndpoint: '/api/moodboard-2-feed/counts',
    moodboardEndpoint: '/api/moodboard-2-feed/moodboard',
    promptEndpoint: '/api/moodboard-2-feed/prompt',
    totalPhases: 5,
    phaseSummary: 'Krea Interior ➔ Claude Prompt ➔ Nano Banana Pro Blending ➔ Reference Auto-Attach ➔ Editorial Flat-Lay Conversion',
    fixtures: MOODBOARD_2_FEED_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'one-product-3-styles',
    name: '1 Product, 3 Styles Feed',
    format: 'feed',
    subtabIndex: 4,
    subTabLabel: '1 Product, 3 Styles',
    runEndpoint: '/api/one-product-3-styles/run',
    statusEndpoint: '/api/one-product-3-styles/status',
    stopEndpoint: '/api/one-product-3-styles/stop',
    countsEndpoint: '/api/one-product-3-styles/counts',
    moodboardEndpoint: '/api/one-product-3-styles/moodboard',
    promptEndpoint: '/api/one-product-3-styles/prompt',
    totalPhases: 4,
    phaseSummary: 'Akeneo Scrape (Shopify Dedup) ➔ Krea 3 Interiors ➔ Claude Prompt Analysis ➔ Nano Banana Pro Multi-Blend + Logo',
    fixtures: ONE_PRODUCT_THREE_STYLES_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'day-night-feed',
    name: 'Day & Night Feed',
    format: 'feed',
    subtabIndex: 5,
    subTabLabel: 'Day & Night',
    runEndpoint: '/api/day-night-feed/run',
    statusEndpoint: '/api/day-night-feed/status',
    stopEndpoint: '/api/day-night-feed/stop',
    countsEndpoint: '/api/day-night-feed/counts',
    moodboardEndpoint: '/api/day-night-feed/moodboard',
    promptEndpoint: '/api/day-night-feed/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scraper ➔ Krea 4:5 Interior ➔ Claude Prompt Analysis ➔ Daytime Room Blending ➔ Night Transformation',
    fixtures: DAY_NIGHT_FEED_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'product-showcase-feed',
    name: 'Product Showcase Feed',
    format: 'feed',
    subtabIndex: 6,
    subTabLabel: 'Product Showcase',
    runEndpoint: '/api/product-showcase-feed/run',
    statusEndpoint: '/api/product-showcase-feed/status',
    stopEndpoint: '/api/product-showcase-feed/stop',
    countsEndpoint: '/api/product-showcase-feed/counts',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape 3 Active Items ➔ 3-Podium Group Slide ➔ 3 Solo Showcase Slides ➔ Final 4-Slide Assembly',
    fixtures: PRODUCT_SHOWCASE_FEED_FIXTURES,
    hasMoodboard: false,
    hasPrompt: false,
  },

  // --- Reel Pipelines ---
  {
    type: 'product-closeup-reel',
    name: 'Product Closeup Reel',
    format: 'reel',
    subtabIndex: 0,
    subTabLabel: 'Product Closeup',
    runEndpoint: '/api/product-closeup-reel/run',
    statusEndpoint: '/api/product-closeup-reel/status',
    stopEndpoint: '/api/product-closeup-reel/stop',
    countsEndpoint: '/api/product-closeup-reel/counts',
    moodboardEndpoint: '/api/product-closeup-reel/moodboard',
    promptEndpoint: '/api/product-closeup-reel/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interior ➔ Claude Prompt ➔ Banana Blend ➔ FFmpeg Video Reel',
    fixtures: PRODUCT_CLOSEUP_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'day-night-reel',
    name: 'Day & Night Reel',
    format: 'reel',
    subtabIndex: 1,
    subTabLabel: 'Day & Night',
    runEndpoint: '/api/day-night-reel/run',
    statusEndpoint: '/api/day-night-reel/status',
    stopEndpoint: '/api/day-night-reel/stop',
    countsEndpoint: '/api/day-night-reel/counts',
    moodboardEndpoint: '/api/day-night-reel/moodboard',
    promptEndpoint: '/api/day-night-reel/prompt',
    totalPhases: 7,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interior ➔ Claude Vision ➔ Banana Blend ➔ Grok Video ➔ Audio ➔ FFmpeg Concat',
    fixtures: DAY_NIGHT_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'before-after-reel',
    name: 'Before & After Reel',
    format: 'reel',
    subtabIndex: 2,
    subTabLabel: 'Before & After',
    runEndpoint: '/api/before-after-reel/run',
    statusEndpoint: '/api/before-after-reel/status',
    stopEndpoint: '/api/before-after-reel/stop',
    countsEndpoint: '/api/before-after-reel/counts',
    moodboardEndpoint: '/api/before-after-reel/moodboard',
    promptEndpoint: '/api/before-after-reel/prompt',
    totalPhases: 6,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interior ➔ Claude Vision ➔ Banana Blend ➔ Multiple Angles ➔ FFmpeg Slideshow',
    fixtures: BEFORE_AFTER_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'style-reel-slideshow',
    name: 'Style Reel Slideshow',
    format: 'reel',
    subtabIndex: 3,
    subTabLabel: 'Style Reel Slideshow',
    runEndpoint: '/api/style-reel-slideshow/run',
    statusEndpoint: '/api/style-reel-slideshow/status',
    stopEndpoint: '/api/style-reel-slideshow/stop',
    countsEndpoint: '/api/style-reel-slideshow/counts',
    moodboardEndpoint: '/api/style-reel-slideshow/moodboard',
    promptEndpoint: '/api/style-reel-slideshow/prompt',
    totalPhases: 5,
    phaseSummary: 'Multi-Category Scrape ➔ Sequential Krea Interiors ➔ Claude Vision ➔ Banana Blend ➔ FFmpeg Slideshow',
    fixtures: STYLE_REEL_SLIDESHOW_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'moodboard-reel',
    name: 'Moodboard Reel',
    format: 'reel',
    subtabIndex: 4,
    subTabLabel: 'Moodboard',
    runEndpoint: '/api/moodboard-reel/run',
    statusEndpoint: '/api/moodboard-reel/status',
    stopEndpoint: '/api/moodboard-reel/stop',
    countsEndpoint: '/api/moodboard-reel/counts',
    moodboardEndpoint: '/api/moodboard-reel/moodboard',
    promptEndpoint: '/api/moodboard-reel/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea Interiors ➔ Claude Vision ➔ Banana Blend ➔ Template Conversion & Video Reel',
    fixtures: MOODBOARD_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'one-product-three-styles-reel',
    name: '1 Product, 3 Styles Reel',
    format: 'reel',
    subtabIndex: 5,
    subTabLabel: '1 Product, 3 Styles',
    runEndpoint: '/api/one-product-3-styles-reel/run',
    statusEndpoint: '/api/one-product-3-styles-reel/status',
    stopEndpoint: '/api/one-product-3-styles-reel/stop',
    countsEndpoint: '/api/one-product-3-styles-reel/counts',
    moodboardEndpoint: '/api/one-product-3-styles-reel/moodboard',
    promptEndpoint: '/api/one-product-3-styles-reel/prompt',
    totalPhases: 5,
    phaseSummary: 'Akeneo Scrape ➔ Krea 9:16 Interiors ➔ Claude Vision ➔ Banana Blend ➔ YOLO Tagging ➔ Silent Reel MP4',
    fixtures: ONE_PRODUCT_THREE_STYLES_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
  {
    type: 'one-at-a-time-lights-reel',
    name: 'One at a time Lights Reel',
    format: 'reel',
    subtabIndex: 6,
    subTabLabel: 'One at a time Lights',
    runEndpoint: '/api/one-at-a-time-lights-reel/run',
    statusEndpoint: '/api/one-at-a-time-lights-reel/status',
    stopEndpoint: '/api/one-at-a-time-lights-reel/stop',
    countsEndpoint: '/api/one-at-a-time-lights-reel/counts',
    moodboardEndpoint: '/api/one-at-a-time-lights-reel/moodboard',
    promptEndpoint: '/api/one-at-a-time-lights-reel/prompt',
    totalPhases: 6,
    phaseSummary: 'Akeneo 3-Fixture Scrape ➔ Krea 9:16 Interior ➔ Claude Vision Prompt ➔ Initial Room Blend ➔ 3 YOLO-Tagged Lighting Variations ➔ FFmpeg In-Place Crossfade Mux + Outro',
    fixtures: ONE_AT_A_TIME_LIGHTS_REEL_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },

  // --- Ad Cover Pipeline ---
  {
    type: 'ad-cover',
    name: 'Ad Cover',
    format: 'adcover',
    subtabIndex: 0,
    subTabLabel: 'Chandelier',
    runEndpoint: '/api/ad-cover/run',
    statusEndpoint: '/api/ad-cover/status',
    stopEndpoint: '/api/ad-cover/stop',
    countsEndpoint: '/api/ad-cover/counts',
    moodboardEndpoint: '/api/ad-cover/moodboard',
    promptEndpoint: '/api/ad-cover/prompt',
    totalPhases: 7,
    phaseSummary: 'Akeneo Scrape ➔ Krea 1:1 Interior ➔ Claude Blending Prompt ➔ Nano Banana Pro Blend ➔ Local Pillow 1:1 ➔ Nano Banana Pro 9:16 Story ➔ Local Pillow 9:16 Story',
    fixtures: AD_COVER_FIXTURES,
    hasMoodboard: true,
    hasPrompt: true,
  },
];

export const PIPELINES_BY_KEY: Record<string, PipelineConfig> = PIPELINES.reduce(
  (acc, p) => ({ ...acc, [p.type]: p }),
  {} as Record<string, PipelineConfig>
);

export const getPipelineConfig = (tab: TabType, subtabIdx: number): PipelineConfig | undefined => {
  return PIPELINES.find(p => p.format === tab && p.subtabIndex === subtabIdx);
};

export const getPipelineByType = (type: PipelineType): PipelineConfig | undefined => {
  if (!type) return undefined;
  return PIPELINES_BY_KEY[type];
};

export const getPipelineHeaderTitle = (tab: TabType, subtabIdx: number): string => {
  const cfg = getPipelineConfig(tab, subtabIdx);
  if (!cfg) return 'Lighting Fixtures Progress';
  return `${cfg.name} Fixtures & Airtable Progress`;
};
